version: "3.7"

services:

  app_proxy:
    environment:
      APP_HOST: minecraft-auto-mcs_auto-mcs_1
      APP_PORT: 4000

  auto-mcs:
    image: macarooniman/auto-mcs:2.4@sha256:d9f44be5218bc1af6046c1106bbf032c992fbdaa3f2e9fb8024aba6694a81ef9
    restart: on-failure
    stdin_open: true
    tty: true

    environment:
      WEB_PORT: "8080"
      WEB_USERNAME: "admin"
      WEB_PASSWORD: "auto-mcs"

    ports:
      - "7001:7001"
      - "25565:25565"

    extra_hosts:
      - "host.docker.internal:host-gateway"

    volumes:
      - ${APP_DATA_DIR}/data:/root/.auto-mcs
